[package]
name = "migate"
version = "0.1.0"
edition = "2024"

[dependencies]
event-listener = "5"
serde = { version = "1", features = ["derive"] }
serde_json = "1"
sha2 = "0.11"
uuid = { version = "1", features = ["v4"] }
tempfile = "3"

futures-lite = "2"
async-io = "2"
rand = "0.10"
rs-matter = { git = "https://github.com/project-chip/rs-matter.git", rev = "5c111e94827e685f8052975c1c6a391cb5298b7f", features = ["astro-dnssd", "groups"] }
embassy-time-queue-utils = { version = "0.3", features = ["generic-queue-64"] }
log = "0.4"
blocking = "1"
async-signal = "0.2"
env_logger = "0.11"
